language: ruby

rvm:
  - 2.4

before_script:
  - gem install awesome_bot

script:
  - awesome_bot readme.md --white-list travis-ci.org,creativecommons.org,example.com,github.com/tensorlayer/tensorlayer,tensorlayer.readthedocs.io,tensorlayer.org
  # - awesome_bot README.md -t 5 --allow-timeout --allow-dupe --allow-redirect
