language: ruby

rvm:
  - 2.4.1
  
notifications:
  email: false

before_script:
  - gem install awesome_bot

script:
  - awesome_bot readme.md --white-list creativecommons.org,example.com,tensorlayer.org,arxiv.org/abs/,github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_inceptionV3_tfslim.py,karpathy.github.io/2015/05/21/rnn-effectiveness/,karpathy.github.io/2016/05/31/rl/
  # - awesome_bot README.md -t 5 --allow-timeout --allow-dupe --allow-redirect
